# permissions for end users to edit bikesales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bikesales-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-operator-02
    app.kubernetes.io/part-of: kube-operator-02
    app.kubernetes.io/managed-by: kustomize
  name: bikesales-editor-role
rules:
- apiGroups:
  - zoli.com
  resources:
  - bikesales
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zoli.com.zoli.com
  resources:
  - bikesales/status
  verbs:
  - get
