# permissions for end users to view myowners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: myowner-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-operator-02
    app.kubernetes.io/part-of: kube-operator-02
    app.kubernetes.io/managed-by: kustomize
  name: myowner-viewer-role
rules:
- apiGroups:
  - zoli.com.zoli.com
  resources:
  - myowners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zoli.com.zoli.com
  resources:
  - myowners/status
  verbs:
  - get
